name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🍳 Copy files to server on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: 🤔 Checkout
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./front-end/
          server-dir: /wwwroot/lkzstudio/ch/composition/